// Markdown Spec exporter — converts a VisionMap into a structured Markdown
// document optimized for LLM/agent consumption and Spec generation.

import type { VisionMap, VisionNode, NodeCategory } from "@/lib/vision-map";
import { getCategoryMeta } from "@/lib/vision-map";
import { ANCLORA_APPS } from "@/lib/anclora-ecosystem";

/**
 * Convert a VisionMap into a comprehensive Markdown Spec document.
 * The document is structured so an LLM agent can parse it and generate
 * a full implementation Spec (architecture, API contracts, data model,
 * phases, testing, deployment, etc.).
 */
export function mapToSpecMarkdown(
  map: VisionMap,
  options: { palette?: string; includePrompt?: boolean } = {}
): string {
  const { includePrompt = true } = options;
  const nodes = map.nodes;
  const byCat = (c: NodeCategory) => nodes.filter((n) => n.category === c);

  const ideaNode = byCat("idea")[0];
  const objectives = byCat("objective");
  const priorities = byCat("priority");
  const steps = byCat("step");
  const nexts = byCat("next");
  const risks = byCat("risk");
  const tools = byCat("tool");
  const costs = byCat("cost");
  const kpis = byCat("kpi");
  const stakeholders = byCat("stakeholder");
  const timelines = byCat("timeline");

  const totalCost = costs.reduce((sum, c) => sum + (c.cost || 0), 0);
  const now = new Date();
  const dateStr = now.toISOString().split("T")[0];
  const dateTimeStr = now.toLocaleString("es-ES");

  // Apps referenced in the map (by slug)
  const appSlugs = new Set<string>(map.apps || []);
  tools.forEach((t) => {
    if (t.appSlug) appSlugs.add(t.appSlug);
  });
  const referencedApps = ANCLORA_APPS.filter((a) => appSlugs.has(a.slug));

  const lines: string[] = [];

  // ============ Header ============
  lines.push(`# Spec: ${ideaNode?.title || map.idea}`);
  lines.push("");
  lines.push("> **Generated by AncloraVisionFlow** — Mapa visual convertido a Spec plan para agentes de IA.");
  lines.push(">");
  lines.push(`> - **Fecha de generación**: ${dateTimeStr}`);
  lines.push(`> - **Ecosistema**: Anclora Group`);
  lines.push(`> - **Apps Anclora implicadas**: ${referencedApps.map((a) => a.name).join(", ") || "Ninguna específica"}`);
  lines.push(`> - **Total de nodos**: ${nodes.length} (${objectives.length} objetivos, ${steps.length} pasos, ${risks.length} riesgos, ${kpis.length} KPIs, ${stakeholders.length} stakeholders, ${timelines.length} hitos)`);
  lines.push(`> - **Coste total estimado**: ${totalCost.toLocaleString("es-ES")} €`);
  lines.push("");
  lines.push("---");
  lines.push("");

  // ============ Executive Summary ============
  lines.push(`## 1. Resumen Ejecutivo`);
  lines.push("");
  lines.push(`**Idea original del usuario:**`);
  lines.push("");
  lines.push(`> ${map.idea}`);
  lines.push("");
  lines.push(`**Núcleo del proyecto:**`);
  lines.push("");
  lines.push(`${ideaNode?.description || map.idea}`);
  lines.push("");
  lines.push(`**Síntesis estratégica:**`);
  lines.push("");
  lines.push(`${map.summary}`);
  lines.push("");

  // ============ Objectives ============
  if (objectives.length > 0) {
    lines.push(`## 2. Objetivos`);
    lines.push("");
    objectives.forEach((o, i) => {
      lines.push(`### OBJ-${i + 1}: ${o.title}`);
      lines.push("");
      lines.push(`${o.description}`);
      lines.push("");
      if (o.bullets && o.bullets.length > 0) {
        lines.push(`**Criterios de éxito:**`);
        lines.push("");
        o.bullets.forEach((b) => lines.push(`- ${b}`));
        lines.push("");
      }
    });
  }

  // ============ KPIs ============
  if (kpis.length > 0) {
    lines.push(`## 3. Indicadores Clave de Rendimiento (KPIs)`);
    lines.push("");
    lines.push(`| ID | KPI | Descripción | Target | Actual | Unidad | Progreso |`);
    lines.push(`|----|-----|-------------|--------|--------|--------|----------|`);
    kpis.forEach((k, i) => {
      const target = parseFloat(k.target || "0");
      const current = parseFloat(k.current || "0");
      const pct = isNaN(target) || target === 0
        ? "N/A"
        : `${Math.min(100, Math.round((current / target) * 100))}%`;
      const desc = (k.description || "").replace(/\|/g, "\\|").replace(/\n/g, " ").slice(0, 80);
      lines.push(
        `| KPI-${i + 1} | ${k.title} | ${desc} | ${k.target || "N/A"} | ${k.current || "N/A"} | ${k.unit || ""} | ${pct} |`
      );
    });
    lines.push("");
  }

  // ============ Priorities ============
  if (priorities.length > 0) {
    lines.push(`## 4. Prioridades Estratégicas`);
    lines.push("");
    priorities.forEach((p, i) => {
      const priorityIcon = p.priority === "alta" ? "🔴" : p.priority === "media" ? "🟡" : "🟢";
      lines.push(`### PRI-${i + 1} ${priorityIcon} [${(p.priority || "media").toUpperCase()}]: ${p.title}`);
      lines.push("");
      lines.push(`${p.description}`);
      lines.push("");
    });
  }

  // ============ Execution Plan ============
  if (steps.length > 0) {
    lines.push(`## 5. Plan de Ejecución`);
    lines.push("");
    steps.forEach((s, i) => {
      lines.push(`### STEP-${i + 1}: ${s.title}`);
      lines.push("");
      lines.push(`${s.description}`);
      lines.push("");
      const meta: string[] = [];
      if (s.time) meta.push(`**Tiempo estimado**: ${s.time}`);
      if (s.owner) meta.push(`**Responsable**: ${s.owner}`);
      if (meta.length > 0) {
        lines.push(meta.join(" · "));
        lines.push("");
      }
    });
  }

  // ============ Next Steps ============
  if (nexts.length > 0) {
    lines.push(`## 6. Próximos Pasos Inmediatos`);
    lines.push("");
    nexts.forEach((n, i) => {
      lines.push(`- [ ] **NEXT-${i + 1}**: ${n.title} — ${n.description}`);
    });
    lines.push("");
  }

  // ============ Risk Management ============
  if (risks.length > 0) {
    lines.push(`## 7. Gestión de Riesgos`);
    lines.push("");
    risks.forEach((r, i) => {
      lines.push(`### RISK-${i + 1}: ${r.title}`);
      lines.push("");
      lines.push(`${r.description}`);
      lines.push("");
      if (r.bullets && r.bullets.length > 0) {
        lines.push(`**Mitigaciones:**`);
        lines.push("");
        r.bullets.forEach((b) => lines.push(`- ${b}`));
        lines.push("");
      }
    });
  }

  // ============ Tools ============
  if (tools.length > 0 || referencedApps.length > 0) {
    lines.push(`## 8. Stack Tecnológico y Herramientas`);
    lines.push("");

    if (referencedApps.length > 0) {
      lines.push(`### Apps del Ecosistema Anclora`);
      lines.push("");
      referencedApps.forEach((app) => {
        lines.push(`#### \`${app.slug}\` — ${app.name}`);
        lines.push("");
        lines.push(`**Tagline**: ${app.tagline}`);
        lines.push("");
        lines.push(`**Descripción**: ${app.description}`);
        lines.push("");
        lines.push(`**Stack**: ${app.stack.join(", ")}`);
        lines.push("");
        lines.push(`**Capacidades clave:**`);
        lines.push("");
        app.capabilities.forEach((c) => lines.push(`- ${c}`));
        lines.push("");
      });
    }

    const externalTools = tools.filter((t) => !t.appSlug);
    if (externalTools.length > 0) {
      lines.push(`### Herramientas Externas`);
      lines.push("");
      externalTools.forEach((t) => {
        lines.push(`- **${t.title}**: ${t.description}`);
      });
      lines.push("");
    }
  }

  // ============ Budget ============
  if (costs.length > 0) {
    lines.push(`## 9. Estimación de Presupuesto`);
    lines.push("");
    lines.push(`| ID | Partida | Descripción | Coste (€) |`);
    lines.push(`|----|---------|-------------|-----------|`);
    costs.forEach((c, i) => {
      const desc = (c.description || "").replace(/\|/g, "\\|").replace(/\n/g, " ").slice(0, 100);
      lines.push(
        `| COST-${i + 1} | ${c.title} | ${desc} | ${(c.cost || 0).toLocaleString("es-ES")} |`
      );
    });
    lines.push(`| | | **TOTAL** | **${totalCost.toLocaleString("es-ES")} €** |`);
    lines.push("");
  }

  // ============ Stakeholders ============
  if (stakeholders.length > 0) {
    lines.push(`## 10. Stakeholders`);
    lines.push("");
    lines.push(`| ID | Stakeholder | Rol | Contacto | Descripción |`);
    lines.push(`|----|-------------|-----|----------|-------------|`);
    stakeholders.forEach((s, i) => {
      const desc = (s.description || "").replace(/\|/g, "\\|").replace(/\n/g, " ").slice(0, 80);
      lines.push(
        `| STK-${i + 1} | ${s.title} | ${s.role || "N/D"} | ${s.contact || "N/D"} | ${desc} |`
      );
    });
    lines.push("");
  }

  // ============ Timeline ============
  if (timelines.length > 0) {
    lines.push(`## 11. Cronograma de Hitos`);
    lines.push("");
    // Sort by date if possible
    const sortedTimelines = [...timelines].sort((a, b) => {
      const da = a.date || "";
      const db = b.date || "";
      return da.localeCompare(db);
    });
    lines.push(`| ID | Hito | Fecha | Crítico | Descripción |`);
    lines.push(`|----|------|-------|---------|-------------|`);
    sortedTimelines.forEach((t, i) => {
      const desc = (t.description || "").replace(/\|/g, "\\|").replace(/\n/g, " ").slice(0, 80);
      const critical = t.milestone ? "⭐ Sí" : "No";
      lines.push(
        `| TL-${i + 1} | ${t.title} | ${t.date || "N/D"} | ${critical} | ${desc} |`
      );
    });
    lines.push("");
  }

  // ============ Structured Data (JSON) ============
  lines.push(`## 12. Datos Estructurados (JSON para parsing programático)`);
  lines.push("");
  lines.push("```json");
  lines.push(JSON.stringify(
    {
      idea: map.idea,
      summary: map.summary,
      apps: map.apps,
      generatedAt: map.generatedAt,
      nodes: map.nodes.map((n) => ({
        id: n.id,
        category: n.category,
        title: n.title,
        description: n.description,
        ...(n.bullets ? { bullets: n.bullets } : {}),
        ...(n.cost !== undefined ? { cost: n.cost } : {}),
        ...(n.priority ? { priority: n.priority } : {}),
        ...(n.appSlug ? { appSlug: n.appSlug } : {}),
        ...(n.time ? { time: n.time } : {}),
        ...(n.owner ? { owner: n.owner } : {}),
        ...(n.target ? { target: n.target } : {}),
        ...(n.current ? { current: n.current } : {}),
        ...(n.unit ? { unit: n.unit } : {}),
        ...(n.role ? { role: n.role } : {}),
        ...(n.contact ? { contact: n.contact } : {}),
        ...(n.date ? { date: n.date } : {}),
        ...(n.milestone !== undefined ? { milestone: n.milestone } : {}),
      })),
      connections: map.connections,
    },
    null,
    2
  ));
  lines.push("```");
  lines.push("");

  // ============ Prompt for LLM Agent ============
  if (includePrompt) {
    lines.push(`---`);
    lines.push("");
    lines.push(`## Prompt para Agente de IA — Generación de Spec Técnico`);
    lines.push("");
    lines.push(`Eres un arquitecto de software experto del ecosistema Anclora Group. A partir del plan estructurado arriba (generado por AncloraVisionFlow), genera un **Spec técnico completo** en Markdown que permita a un equipo de desarrollo ejecutar el proyecto de principio a fin.`);
    lines.push("");
    lines.push(`### Estructura requerida del Spec:`);
    lines.push("");
    lines.push(`1. **Resumen Ejecutivo Técnico** — traducción del plan de negocio a requisitos técnicos.`);
    lines.push(`2. **Arquitectura del Sistema** — diagrama de componentes (texto), flujo de datos, decisiones de arquitectura (monolith vs microservices, sync vs async, etc.).`);
    lines.push(`3. **Modelo de Datos** — entidades, atributos, relaciones, estrategia de almacenamiento (PostgreSQL, SQLite, Redis, etc.), migraciones.`);
    lines.push(`4. **Contratos de API** — endpoints REST/GraphQL con método, path, request/response schemas, códigos de error, ejemplos curl.`);
    lines.push(`5. **Integraciones con Anclora** — cómo se integra cada app Anclora referenciada (endpoints, webhooks, eventos, data flow bidireccional).`);
    lines.push(`6. **Plan de Implementación por Fases** — breakdown en sprints de 2 semanas con entregables, dependencias y owners. Mapea cada STEP-N a una fase.`);
    lines.push(`7. **Estrategia de Testing** — unit tests (cobertura mínima 80%), integration tests, E2E tests, estrategia de mocking para apps Anclora.`);
    lines.push(`8. **Plan de Despliegue** — entornos (dev/staging/prod), CI/CD pipeline, estrategia de rollout (blue-green, canary), rollback plan.`);
    lines.push(`9. **Criterios de Aceptación por KPI** — para cada KPI-N, define cómo se mide, qué instrumentación hace falta, y qué triggers el éxito/fracaso.`);
    lines.push(`10. **Gestión de Riesgos Técnicos** — para cada RISK-N, propone mitigaciones técnicas concretas (circuit breakers, retries, feature flags, etc.).`);
    lines.push(`11. **Estimación Detallada** — desglose por componente/fase con story points y horas. Compara con el COST-N del plan original.`);
    lines.push(`12. **Preguntas Abiertas y Decisiones Pendientes** — lista de decisiones que requieren input humano antes de empezar.`);
    lines.push("");
    lines.push(`### Reglas:`);
    lines.push("");
    lines.push(`- Usa los IDs del plan (OBJ-1, STEP-2, KPI-3, etc.) para referenciar elementos de forma trazable.`);
    lines.push(`- Prioriza las apps Anclora del catálogo como soluciones antes de proponer herramientas externas.`);
    lines.push(`- Respeta el budget total de ${totalCost.toLocaleString("es-ES")} € — si la implementación excede, propón fases opcionales.`);
    lines.push(`- Respeta el timeline — si hay conflictos, marca la dependencia bloqueante.`);
    lines.push(`- Genera el Spec en español, en formato Markdown, listo para commit en un repo.`);
    lines.push("");
    lines.push(`### Output esperado:`);
    lines.push("");
    lines.push(`Un único documento Markdown con las 12 secciones arriba, cada una con suficiente detalle para que un developer pueda empezar a codear sin preguntas adicionales. Incluye snippets de código (schemas, tipos TypeScript, ejemplos de API) donde aporte claridad.`);
  }

  return lines.join("\n");
}

/**
 * Trigger a browser download of the Spec Markdown file.
 */
export function downloadSpecMarkdown(map: VisionMap, options?: { palette?: string }) {
  const md = mapToSpecMarkdown(map, options);
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  const safeName =
    (map.idea || "anclora-spec")
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 60) || "anclora-spec";
  link.download = `spec-${safeName}.md`;
  link.href = url;
  link.click();
  URL.revokeObjectURL(url);
}
